version: "3"

services:
  frontend:
      build:
        context: ./chatclient
        dockerfile: Dockerfile
      volumes:
        - ./chatclient:/app/
      ports:
        - "8080:5175"
      image: chatapp-frontend
      container_name: chatclient
      networks:
        - chatApp
      depends_on:
        - backend 
  backend:
      build:
          context: ./chatserver
          dockerfile: Dockerfile
      volumes:
          - ./chatserver:/app/src
      ports:
          - "5000:5500"
      image: chatapp-backend
      container_name: chatserver
      networks:
          - chatApp
networks:
  chatApp:
volumes:
  web-root:
    driver: local
  node_modules:
