version: "3"

services:
  client:
      build:
          context: .
          dockerfile: Dockerfile
      # volumes:
      #     - :/app
      ports:
          - "5175:5175"
      # image: chatclient2
      container_name: chatclient
      networks:
          - chatApp
networks:
  chatApp: