version: "3"

services:
  backend:
      build:
          context: .
          dockerfile: Dockerfile
      volumes:
          - ./chatserver:/app/src
      ports:
          - "5500:5500"
      container_name: chatserver
      networks:
          - chatApp
networks:
  chatApp: